#!/usr/bin/python

def d1(f) :
    def wrapper(*args, **kwargs) :
        args[0]['d1'] = 'd1'
        f(*args, **kwargs)

    return wrapper

def d2(f) :
    def wrapper(*args, **kwargs) :
        args[0]['d2'] = 'd2'
        f(*args, **kwargs)

    return wrapper


@d1
@d2
def f1(m) :
    m['f1'] = 'f1'


m = {}
f1(m)

for k,v in m.iteritems() :
    print '%s : %s' % (k, v)
